### PR TITLE
Various changes

### LINKED ISSUE #3: `brew services list` command can show `error` in Status column
Currently, the app doesn't indicate this, it shows a non-checked state.

It would be nice to show a red dot or some other indicator.

### PR DESCRIPTION
**Pull request by stephank**
I love this! Thanks for taking the time to build it. :)

This PR contains a change to grey out menu items that are not `started` or `stopped` (also sets mixed state on the item), or running as the current user. I have some services running as root (nginx, dnsmasq), and this should also fix #3.

I also removed the query call on startup. Don't believe it adds anything?

I was looking for ways to speed up the menu, but they're all a bit more complicated apparently. We can't directly use launchctl to query services, because they simply don't exist. Looks like the cli actually iterates formulae, so we're stuck in ruby land: https://github.com/Homebrew/homebrew-services/blob/e02fbadb456a52b66fd43f0a23d413a803f1250b/cmd/brew-services.rb#L83-L86

Other thought I had was to maybe query on mouseover, so it'd perhaps be ready on click, but that requires a bit more work creating a custom view.

I guess the most useful thing to do, later, is to make it threaded/async and show a spinner or something.

### CODE REVIEW

**Comment by stephank** [comment]
I've added the async stuff, and did some more cleanup! Whoop! :)

**Comment by stephank** [comment]
Did some more work!

 - `brew` path is now customizable using `defaults`, though no pretty preferences window yet.
 - Doesn't crash when homebrew is not installed / not found. (Just shows no services.)
 - Handles non-zero exit. Shows no services in the menu, and when start/stop fails shows an alert.

**Comment by andrewn** [comment]
Hi @stephank, wow, thanks so much for all this work! I'm really pleased that you find this tool useful :-).

I'm planning on reviewing this PR this weekend. Mainly I just want to test it before merging and building a new release!

P.S. I just added a "Contributors" section to `README.md`. You should add yourself in there too and push another commit.

**Comment by stephank** [comment]
Thanks, all done! :)

**Comment by andrewn** [comment]
This is great stuff, thanks so much for taking the time to improve it so much.

I've created a [new release](https://github.com/andrewn/brew-services-menubar/releases/tag/v2.1.0).

**Comment by stephank** [comment]
Awesome, thanks! :D

**Pull request merged**
